'use client';
import { ArrowRight, Copy, Plus, Save, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
type Role = { id: string; name: string; code: string; users: number; permissions: string[] };
type Permission = { id: string; code: string };
export default function RolesPage() {
  const [roles, setRoles] = useState<Role[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]);
  const [form, setForm] = useState({ id: '', name: '', code: '', permissions: [] as string[] }); const [error, setError] = useState(''); const [saved, setSaved] = useState('');
  async function load() { const r = await fetch('/api/admin/roles'); if (!r.ok) throw new Error('لا تملك صلاحية إدارة الأدوار أو تعذر الاتصال'); const d = await r.json(); setRoles(d.roles); setPermissions(d.permissions); }
  useEffect(() => { void load().catch((e: Error) => setError(e.message)); }, []);
  async function save() { setError(''); setSaved(''); const r = await fetch(`/api/admin/roles${form.id ? '/' + form.id : ''}`, { method: form.id ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.name, code: form.code, permissions: form.permissions }) }); const d = await r.json(); if (!r.ok) { setError(d.message || 'تعذر الحفظ'); return; } await load(); setSaved('تم حفظ الدور والصلاحيات.'); }
  const groups = Array.from(new Set(permissions.map((p) => p.code.split('.')[0])));
  return <main className="management-page"><header className="management-header"><div><a href="/"><ArrowRight size={17} /> لوحة الإدارة</a><h1>الأدوار والصلاحيات</h1></div><ShieldCheck size={28} /></header>{error && <p className="notice error">{error}</p>}{saved && <p className="notice success">{saved}</p>}<div className="permissions-layout"><aside className="roles-list"><button className="primary-button" onClick={() => setForm({ id: '', name: '', code: '', permissions: [] })}><Plus size={17} /> دور جديد</button>{roles.map((r) => <button key={r.id} className={r.id === form.id ? 'role-choice selected' : 'role-choice'} onClick={() => setForm(r)}><strong>{r.name}</strong><small>{r.code} · {r.users} مستخدم</small></button>)}</aside><section><div className="form-grid"><label className="form-field"><span>اسم الدور</span><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="form-field"><span>رمز الدور</span><input dir="ltr" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} /></label></div>{groups.map((group) => <div key={group} className="permission-group"><h2>{group}</h2>{permissions.filter((p) => p.code.startsWith(group + '.')).map((p) => <label key={p.id}><input type="checkbox" disabled={form.code === 'SUPER_ADMIN'} checked={form.permissions.includes(p.code)} onChange={(e) => setForm({ ...form, permissions: e.target.checked ? [...form.permissions, p.code] : form.permissions.filter((x) => x !== p.code) })} /><span dir="ltr">{p.code}</span></label>)}</div>)}<div className="form-actions"><button className="secondary-button" onClick={() => setForm({ ...form, id: '', code: '', name: form.name + ' نسخة' })}><Copy size={16} /> نسخ الدور</button><button className="primary-button" disabled={form.code === 'SUPER_ADMIN' || !form.code || !form.name} onClick={() => void save()}><Save size={17} /> حفظ</button></div></section></div></main>;
}
