'use client';

import { ArrowRight, BadgeCheck, CheckCircle2, Clock3, LoaderCircle, MapPin, MessageSquareText, Star, Wrench } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

type Technician = { id: string; name: string; specialty: string; yearsExperience: number | null; city: { id: string; nameAr: string } | null;
  serviceRegions: string[]; basePriceLyd: number; availabilityStatus: string; ratingAverage: number; ratingCount: number; completedInspections: number;
  services: { id: string; name: string; priceLyd: number; durationMinutes: number | null }[];
  reviews: { id: string; rating: number; comment: string | null; reviewerName: string; createdAt: string }[] };

export default function TechnicianPublicDetail() {
  const { id } = useParams<{ id: string }>(); const [technician, setTechnician] = useState<Technician | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/platform/technicians/${encodeURIComponent(id)}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.message || 'تعذر تحميل الفني'); setTechnician(body); } catch (caught) { setError(caught instanceof Error ? caught.message : 'تعذر تحميل الفني'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function review(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const response = await fetch(`/api/platform/technicians/${encodeURIComponent(id)}/reviews`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ rating: Number(values.rating), comment: values.comment }) }); const body = await response.json(); if (response.status === 401) { window.location.href = `/auth?returnTo=/technicians/${id}`; return; } if (!response.ok) setError(body.message === 'review.completed_inspection_required' ? 'يمكن إضافة التقييم بعد اكتمال خدمة فحص واحدة على الأقل مع هذا الفني.' : body.message || 'تعذر حفظ التقييم.'); else { setMessage('تم حفظ تقييمك.'); form.reset(); await load(); } setBusy(false); }
  if (loading) return <main className="dealer-public-detail"><div className="public-list-state"><LoaderCircle className="spin" /> جارٍ تحميل الفني...</div></main>;
  if (!technician) return <main className="dealer-public-detail"><div className="public-list-state error">{error || 'الفني غير موجود'}</div></main>;
  return <main className="dealer-public-detail technician-public-detail"><header><a href="/technicians"><ArrowRight size={17} /> كل الفنيين</a><div className="dealer-public-title"><span><Wrench size={34} /></span><div><p><BadgeCheck size={16} /> فني معتمد</p><h1>{technician.name}</h1><small><MapPin size={14} /> {technician.city?.nameAr || 'ليبيا'} · {technician.specialty}</small></div><strong><Star size={18} /> {technician.ratingAverage.toFixed(1)} <small>{technician.ratingCount} تقييم</small></strong></div></header>
    {message && <div className="form-success"><CheckCircle2 size={17} />{message}</div>}{error && <div className="auth-error">{error}</div>}
    <section className="technician-profile-band"><div><Clock3 size={18} /><strong>{technician.yearsExperience ?? 0}</strong><span>سنوات خبرة</span></div><div><Wrench size={18} /><strong>{technician.completedInspections}</strong><span>فحص مكتمل</span></div><div><Star size={18} /><strong>{technician.ratingAverage.toFixed(1)}</strong><span>متوسط التقييم</span></div></section>
    <div className="dealer-review-layout"><section className="portal-section"><div className="section-title"><div><small>الخدمات المتاحة</small><h2>الخدمات والأسعار</h2></div><Wrench size={21} /></div><div className="technician-service-detail">{technician.services.map((service) => <div key={service.id}><span>{service.name}<small>{service.durationMinutes ? `${service.durationMinutes} دقيقة` : 'المدة حسب الحالة'}</small></span><strong>{service.priceLyd.toLocaleString('ar-LY')} د.ل</strong></div>)}</div><div className="section-title review-heading"><div><small>تجارب مؤكدة</small><h2>تقييمات العملاء</h2></div><MessageSquareText size={21} /></div>{technician.reviews.map((item) => <article className="dealer-review" key={item.id}><div><strong>{item.reviewerName}</strong><span>{'★'.repeat(item.rating)}{'☆'.repeat(5 - item.rating)}</span></div><p>{item.comment || 'تقييم دون تعليق'}</p><time>{new Date(item.createdAt).toLocaleDateString('ar-LY')}</time></article>)}{!technician.reviews.length && <p className="muted-copy">لا توجد تقييمات بعد.</p>}</section>
      <form className="portal-section" onSubmit={review}><div className="section-title"><div><small>بعد اكتمال الفحص</small><h2>قيّم الفني</h2></div><Star size={21} /></div><p className="muted-copy">يقبل النظام التقييم فقط من مستخدم لديه طلب فحص مكتمل مع هذا الفني.</p><label><span>التقييم</span><select required name="rating" defaultValue="5"><option value="5">5 - ممتاز</option><option value="4">4 - جيد جداً</option><option value="3">3 - جيد</option><option value="2">2 - ضعيف</option><option value="1">1 - سيئ</option></select></label><label><span>التعليق</span><textarea name="comment" maxLength={1000} rows={6} placeholder="اكتب تجربتك بعد انتهاء الخدمة" /></label><button className="auth-submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <MessageSquareText size={18} />} حفظ التقييم</button></form></div>
  </main>;
}
