'use client';

import { ArrowRight, CheckCircle2, CircleDollarSign, Eye, EyeOff, LoaderCircle, MessageSquareText, ShieldAlert, Star, WalletCards, Wrench } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

type Detail = {
  technician: { id: string; name: string; phone: string; specialty: string; yearsExperience: number | null; basePriceLyd: number;
    availabilityStatus: string; approvalStatus: string; ratingAverage: number; ratingCount: number; completedInspections: number;
    city: { id: string; nameAr: string } | null; serviceRegions: string[]; account: { id: string; status: string; phoneVerified: boolean; lastLoginAt: string | null; createdAt: string };
    services: { id: string; name: string; priceLyd: number; durationMinutes: number | null }[] };
  stats: { requests: number; completed: number; cancelled: number; completedServiceValueLyd: number };
  inspections: { id: string; inspectionType: string; status: string; priceLyd: number; scheduledAt: string | null; createdAt: string;
    requester: { id: string; fullName: string | null; phone: string | null }; vehicle: { id: string; lotNumber: string; make: string; model: string; year: number } }[];
  reviews: { id: string; rating: number; comment: string | null; isHidden: boolean; moderationReason: string | null; createdAt: string;
    reviewer: { id: string; fullName: string | null; phone: string | null } }[];
};
type Wallet = { summary: { balanceLyd: number; rechargeCount: number; rechargeTotalLyd: number; totalSpentLyd: number } };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, cache: 'no-store', headers: { 'content-type': 'application/json', ...init?.headers } }); const body = await response.json() as T & { message?: string }; if (!response.ok) throw new Error(body.message || 'تعذر تنفيذ العملية'); return body; }
const money = (value: number) => `${value.toLocaleString('ar-LY', { minimumFractionDigits: 3, maximumFractionDigits: 3 })} د.ل`;
const date = (value: string | null) => value ? new Date(value).toLocaleString('ar-LY') : '-';

export default function TechnicianDetailPage() {
  const { id } = useParams<{ id: string }>(); const [data, setData] = useState<Detail | null>(null); const [wallet, setWallet] = useState<Wallet | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const detail = await request<Detail>(`/api/admin/technicians/${encodeURIComponent(id)}`); setData(detail); setWallet(await request<Wallet>(`/api/admin/wallet/users/${encodeURIComponent(detail.technician.account.id)}`)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'تعذر تحميل الفني'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function moderate(reviewId: string, hidden: boolean) { setBusy(reviewId); setError(''); try { await request(`/api/admin/technicians/reviews/${encodeURIComponent(reviewId)}`, { method: 'PATCH', body: JSON.stringify({ hidden, reason: hidden ? 'مخالفة سياسة التقييمات' : undefined }) }); setMessage(hidden ? 'تم إخفاء التقييم مع الاحتفاظ بالسجل.' : 'تمت استعادة التقييم.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'تعذر تعديل التقييم'); } finally { setBusy(''); } }
  if (loading) return <main className="management-page"><div className="loading-state"><LoaderCircle className="spin" /> جارٍ تحميل ملف الفني...</div></main>;
  if (!data || !wallet) return <main className="management-page"><div className="notice error"><ShieldAlert size={18} />{error || 'الفني غير موجود'}</div></main>;
  const { technician, stats } = data;
  return <main className="management-page detail-page">
    <header className="management-header"><div><a href="/technicians"><ArrowRight size={17} /> الفنيون</a><h1>{technician.name}</h1><p>{technician.specialty} · {technician.city?.nameAr || 'مدينة غير محددة'} · <span dir="ltr">{technician.phone}</span></p></div><span className={`status-chip status-${technician.approvalStatus.toLowerCase()}`}>{technician.approvalStatus}</span></header>
    {message && <div className="notice success"><CheckCircle2 size={18} />{message}</div>}{error && <div className="notice error"><ShieldAlert size={18} />{error}</div>}
    <section className="detail-metrics"><Metric icon={<Wrench />} label="طلبات الفحص" value={String(stats.requests)} hint={`${stats.completed} مكتملة`} /><Metric icon={<CircleDollarSign />} label="قيمة الخدمات المكتملة" value={money(stats.completedServiceValueLyd)} /><Metric icon={<Star />} label="التقييم" value={`${technician.ratingAverage.toFixed(1)} / 5`} hint={`${technician.ratingCount} تقييم`} /><Metric icon={<WalletCards />} label="رصيد الفني" value={money(wallet.summary.balanceLyd)} /><Metric icon={<CircleDollarSign />} label="مرات التمويل" value={String(wallet.summary.rechargeCount)} hint={money(wallet.summary.rechargeTotalLyd)} /><Metric icon={<ShieldAlert />} label="الطلبات الملغاة" value={String(stats.cancelled)} /></section>
    <div className="detail-columns"><section className="panel detail-section"><div className="panel-header"><div><p className="eyebrow">الحساب والاعتماد</p><h2>بيانات الفني</h2></div><Wrench size={20} /></div><dl className="detail-list"><div><dt>سنوات الخبرة</dt><dd>{technician.yearsExperience ?? 0}</dd></div><div><dt>السعر الأساسي</dt><dd>{money(technician.basePriceLyd)}</dd></div><div><dt>التوفر</dt><dd>{technician.availabilityStatus}</dd></div><div><dt>حالة الحساب</dt><dd>{technician.account.status}</dd></div><div><dt>آخر دخول</dt><dd>{date(technician.account.lastLoginAt)}</dd></div><div><dt>المناطق</dt><dd>{technician.serviceRegions.join('، ') || '-'}</dd></div></dl><a className="secondary-button" href={`/users/${technician.account.id}`}>إدارة الحساب والمحفظة</a></section><section className="panel detail-section"><div className="panel-header"><div><p className="eyebrow">أسعار قابلة للإدارة</p><h2>الخدمات</h2></div></div><div className="detail-stack">{technician.services.map((service) => <div key={service.id}><strong>{service.name}</strong><span>{money(service.priceLyd)}</span><small>{service.durationMinutes ? `${service.durationMinutes} دقيقة` : 'مدة غير محددة'}</small></div>)}</div></section></div>
    <section className="panel detail-table"><div className="panel-header"><div><p className="eyebrow">لا يقبل التقييم إلا بعد اكتمال أحدها</p><h2>طلبات الفحص</h2></div></div>{data.inspections.length ? <div className="table-wrap"><table><thead><tr><th>المستخدم</th><th>السيارة</th><th>الخدمة</th><th>الحالة</th><th>القيمة</th><th>الموعد</th></tr></thead><tbody>{data.inspections.map((item) => <tr key={item.id}><td><a href={`/users/${item.requester.id}`}>{item.requester.fullName || item.requester.phone}</a></td><td>{item.vehicle.make} {item.vehicle.model} {item.vehicle.year}<small>{item.vehicle.lotNumber}</small></td><td>{item.inspectionType}</td><td>{item.status}</td><td>{money(item.priceLyd)}</td><td>{date(item.scheduledAt)}</td></tr>)}</tbody></table></div> : <p className="detail-empty">لا توجد طلبات فحص.</p>}</section>
    <section className="panel detail-table"><div className="panel-header"><div><p className="eyebrow">إخفاء دون حذف</p><h2>تقييمات الفني</h2></div><MessageSquareText size={20} /></div>{data.reviews.length ? <div className="table-wrap"><table><thead><tr><th>المستخدم</th><th>التقييم</th><th>التعليق</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{data.reviews.map((item) => <tr key={item.id}><td><a href={`/users/${item.reviewer.id}`}>{item.reviewer.fullName || item.reviewer.phone}</a></td><td>{item.rating}/5</td><td>{item.comment || 'دون تعليق'}</td><td>{item.isHidden ? 'مخفي' : 'ظاهر'}</td><td><button className="icon-button" disabled={busy === item.id} title={item.isHidden ? 'إظهار' : 'إخفاء'} onClick={() => void moderate(item.id, !item.isHidden)}>{item.isHidden ? <Eye size={16} /> : <EyeOff size={16} />}</button></td></tr>)}</tbody></table></div> : <p className="detail-empty">لا توجد تقييمات.</p>}</section>
  </main>;
}
function Metric({ icon, label, value, hint }: { icon: React.ReactNode; label: string; value: string; hint?: string }) { return <article>{icon}<div><span>{label}</span><strong>{value}</strong>{hint && <small>{hint}</small>}</div></article>; }
