'use client';
import { ArrowRight, Check, CreditCard, Heart, Inbox, Lock, Save, Settings, Star, Wallet } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
type Plan = { id: string; name: string; priceLyd: number; durationDays: number; auctionLimit: number | null };
type Subscription = { id: string; status: string; usedAuctions: number; endsAt: string | null; plan: Plan };
type Order = { id: string; type: string; status: string; totalLyd: number };
type Ledger = { accounts: { currency: string; balanceLyd: number }[]; entries: { id: string; type: string; direction: string; amountLyd: number; createdAt: string }[]; withdrawals: { id: string; status: string; amountLyd: number }[] };
type Row = { id: string; incoming: boolean; status: string; vehicle: { id: string; make: string; model: string; dealerId?: string }; technician?: { id: string; name: string }; scheduledAt?: string; priceLyd?: number; report?: { technicianNotes: string; recommendations: string; overallScore: number } };
const tabs = { wallet: ['المحفظة', Wallet], subscriptions: ['اشتراكات النشر', CreditCard], requests: ['الطلبات', Inbox], favorites: ['المفضلة', Heart], settings: ['الإعدادات', Settings] } as const;
type Tab = keyof typeof tabs;
const statuses: Record<string, string> = { PaymentPending: 'بانتظار الدفع', Pending: 'بانتظار المراجعة', Active: 'فعّال', Paid: 'مدفوع', Completed: 'مكتمل', Accepted: 'مقبول', Delivered: 'بانتظار تأكيد المشتري', ReportSubmitted: 'التقرير جاهز', InProgress: 'قيد التنفيذ', Scheduled: 'مجدول', Rejected: 'مرفوض', RejectedByTechnician: 'رفضه الفني', Cancelled: 'ملغى', Suspended: 'موقوف', Expired: 'منتهي', Refunded: 'مسترد' };
const names: Record<string, string> = { MemberSubscription: 'اشتراك النشر', DealerSubscription: 'اشتراك المعرض', WalletRecharge: 'شحن المحفظة', AuctionDeposit: 'عربون المزاد', AuctionListingFee: 'رسوم نشر المزاد', InspectionFee: 'رسوم الفحص', AdminAdjustment: 'تسوية إدارية', WithdrawalReservation: 'حجز مبلغ الاسترداد', WithdrawalReleased: 'إعادة مبلغ الاسترداد', InspectionRefund: 'استرداد رسوم الفحص', ExternalPayment: 'دفع إلكتروني' };
const money = (n: number) => `${n.toLocaleString('ar-LY')} د.ل`;
async function api<T>(path: string, method = 'GET', data?: unknown): Promise<T> {
  const r = await fetch(`/api/platform/${path}`, { method, cache: 'no-store', ...(data === undefined ? {} : { headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }) });
  if (r.status === 401) { location.href = `/auth?returnTo=${encodeURIComponent(location.pathname + location.search)}`; throw new Error('سجل الدخول أولاً'); }
  const body = await r.json().catch(() => null);
  if (!r.ok) {
    const code = String(body?.message ?? '');
    throw new Error(code.includes('insufficient_balance') ? 'الرصيد غير كافٍ.' : code.includes('auction_commitment') ? 'التأمين مرتبط بمزاد جارٍ. انتظر تسوية الالتزامات.' : code.includes('subscription.') ? 'يلزم اشتراك نشر فعّال وحصة متاحة.' : code.includes('completed_') ? 'التقييم متاح بعد اكتمال الخدمة.' : 'تعذر إكمال العملية. راجع البيانات وحالة الطلب.');
  }
  return body as T;
}
export default function WorkspacePage() {
  const [tab, setTab] = useState<Tab>('wallet'), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [wallet, setWallet] = useState<Ledger | null>(null), [orders, setOrders] = useState<Order[]>([]), [providers, setProviders] = useState<{ code: string; name: string }[]>([]);
  const [subscriptions, setSubscriptions] = useState<{ required: boolean; plans: Plan[]; subscriptions: Subscription[] } | null>(null);
  const [rows, setRows] = useState<{ sales: Row[]; inspections: Row[] }>({ sales: [], inspections: [] }), [incoming, setIncoming] = useState(true);
  const [favorites, setFavorites] = useState<{ id: string; make: string; model: string; year: number }[]>([]);
  const [preferences, setPreferences] = useState({ pushEnabled: true, auctionNotifications: true, messageNotifications: true }), [name, setName] = useState('');
  const [amount, setAmount] = useState(''), [reason, setReason] = useState(''), [provider, setProvider] = useState('');
  const [booking, setBooking] = useState<{ vehicleId: string; inspection: boolean } | null>(null), [technicians, setTechnicians] = useState<{ id: string; name: string; basePriceLyd: number }[]>([]), [technicianId, setTechnicianId] = useState(''), [date, setDate] = useState('');
  const [report, setReport] = useState<{ id: string; technicianNotes: string; recommendations: string; overallScore: number; engine: string; transmission: string; electric: string; chassis: string } | null>(null);
  const [review, setReview] = useState<{ id: string; kind: string; rating: number; comment: string } | null>(null);
  const [currentPassword, setCurrentPassword] = useState(''), [newPassword, setNewPassword] = useState('');
  async function load(view: Tab) {
    try {
      if (view === 'wallet') { setWallet(await api<Ledger>('wallet')); setOrders(await api<Order[]>('payments/orders')); const p = await api<{ code: string; name: string }[]>('payments/providers'); setProviders(p); setProvider((v) => v || p[0]?.code || ''); }
      if (view === 'subscriptions') setSubscriptions(await api('subscriptions/me'));
      if (view === 'requests') setRows(await api('workspace/requests'));
      if (view === 'favorites') setFavorites(await api('account/favorites/vehicles'));
      if (view === 'settings') { const data = await api<{ fullName: string; preferences: typeof preferences }>('workspace/settings'); setName(data.fullName); setPreferences(data.preferences); }
    } catch (e) { setError(e instanceof Error ? e.message : 'تعذر الاتصال'); }
  }
  useEffect(() => { const params = new URLSearchParams(location.search), view = params.get('tab'); if (view && Object.hasOwn(tabs, view)) setTab(view as Tab); const vehicleId = params.get('vehicleId'); if (vehicleId) { const inspection = params.get('action') === 'inspection'; setBooking({ vehicleId, inspection }); if (inspection) void api<typeof technicians>('technicians').then(setTechnicians).catch((e: Error) => setError(e.message)); } }, []);
  useEffect(() => { void load(tab); if (!['wallet', 'requests'].includes(tab)) return; const timer = setInterval(() => void load(tab), 15000); return () => clearInterval(timer); }, [tab]);
  async function run(task: () => Promise<unknown>, message = 'تم حفظ العملية') {
    if (busy) return;
    setBusy(true); setError(''); setNotice('');
    try { await task(); await load(tab); setNotice(message); }
    catch (e) { setError(e instanceof Error ? e.message : 'تعذر الاتصال'); }
    finally { setBusy(false); }
  }
  async function topup(e: FormEvent) {
    e.preventDefault();
    await run(async () => {
      const order = await api<{ id: string }>('payments/wallet/topups', 'POST', { amountLyd: amount, idempotencyKey: crypto.randomUUID() });
      const p = await api<{ checkoutUrl: string }>('payments', 'POST', { orderId: order.id, provider, idempotencyKey: crypto.randomUUID() });
      if (!p.checkoutUrl?.startsWith('https://')) throw new Error('لم يوفر مزود الدفع رابطاً صالحاً.');
      location.href = p.checkoutUrl;
    }, 'الدفع قيد المعالجة، يُضاف الرصيد بعد تأكيد المزود.');
  }
  function card(r: Row, inspection: boolean) {
    const kind = inspection ? 'inspections' : 'sales';
    const action = (name: string, label: string) => <button disabled={busy} onClick={() => void run(() => api(`workspace/${kind}/${r.id}`, 'PATCH', { action: name }))}><Check size={16} />{label}</button>;
    return <article className="workspace-request" key={r.id}><h3>{r.vehicle.make} {r.vehicle.model}</h3><span>{statuses[r.status] ?? r.status}</span>{inspection && <p>{r.technician?.name} · {money(r.priceLyd ?? 0)} · {r.scheduledAt && new Date(r.scheduledAt).toLocaleString('ar-LY')}</p>}
      {r.report && <details><summary>تقرير الفحص · {r.report.overallScore}/100</summary><p>{r.report.technicianNotes}</p><p>{r.report.recommendations}</p></details>}
      <div className="workspace-actions">{incoming && r.status === (inspection ? 'Paid' : 'Pending') && action('accept', 'قبول')}{incoming && ['Pending', 'Paid', 'PaymentPending'].includes(r.status) && action('reject', 'رفض')}{incoming && r.status === (inspection ? 'Scheduled' : 'Accepted') && action(inspection ? 'start' : 'deliver', inspection ? 'بدء الفحص' : 'تأكيد التسليم')}
      {incoming && inspection && r.status === 'InProgress' && <button onClick={() => setReport({ id: r.id, technicianNotes: '', recommendations: '', overallScore: 0, engine: '', transmission: '', electric: '', chassis: '' })}>كتابة التقرير</button>}
      {!incoming && ['Pending', 'Accepted', 'PaymentPending', 'Paid', 'Scheduled'].includes(r.status) && action('cancel', 'إلغاء')}{!incoming && ['Delivered', 'ReportSubmitted'].includes(r.status) && action('complete', 'تأكيد الاكتمال')}{!incoming && r.status === 'PaymentPending' && <button onClick={() => setTab('wallet')}><Wallet size={17} />إكمال الدفع</button>}
      {!incoming && r.status === 'Completed' && (inspection || r.vehicle.dealerId) && <button onClick={() => setReview({ id: inspection ? r.technician!.id : r.vehicle.dealerId!, kind: inspection ? 'technicians' : 'dealers', rating: 5, comment: '' })}><Star size={17} />تقييم الخدمة</button>}</div></article>;
  }
  return <main className="account-page"><header className="account-header"><a href="/account"><ArrowRight size={17} /> حسابي</a><h1>{tabs[tab][0]}</h1></header><nav className="workspace-tabs">{Object.entries(tabs).map(([key, [label, Icon]]) => <button key={key} aria-pressed={tab === key} onClick={() => { setError(''); setNotice(''); setTab(key as Tab); }}><Icon size={17} />{label}</button>)}</nav>
    {error && <p role="alert" className="auth-error">{error}</p>}{notice && <p role="status">{notice}</p>}
    {booking && <form className="workspace-form" onSubmit={(e) => { e.preventDefault(); void run(async () => { await api(`workspace/${booking.inspection ? 'inspections' : 'sales'}`, 'POST', { vehicleId: booking.vehicleId, ...(booking.inspection ? { technicianId, scheduledAt: new Date(date).toISOString(), notes: reason, idempotencyKey: crypto.randomUUID() } : { message: reason }) }); setBooking(null); setTab('requests'); }, booking.inspection ? 'تم إنشاء طلب الفحص. أكمل الدفع من المحفظة.' : 'تم إرسال طلب الشراء'); }}><h2>{booking.inspection ? 'طلب فحص المركبة' : 'طلب شراء المركبة'}</h2>{booking.inspection && <><label>الفني والسعر<select required value={technicianId} onChange={(e) => setTechnicianId(e.target.value)}><option value="">اختر الفني</option>{technicians.map((t) => <option key={t.id} value={t.id}>{t.name} · {money(t.basePriceLyd)}</option>)}</select></label><label>الموعد<input type="datetime-local" required value={date} onChange={(e) => setDate(e.target.value)} /></label></>}<label>ملاحظات<textarea maxLength={1000} value={reason} onChange={(e) => setReason(e.target.value)} /></label><button disabled={busy} className="auth-submit">إرسال الطلب</button></form>}
    {tab === 'wallet' && <><section className="wallet-balance"><Wallet size={24} /><span>الرصيد المتاح</span><strong>{money(wallet?.accounts.find((a) => a.currency === 'LYD')?.balanceLyd ?? 0)}</strong></section><p>رصيد المزايدة تأمين للأهلية ولا يُخصم عند المزايدة. يمكنك طلب استرداده بعد نهاية المزاد وتسوية الالتزامات. رسوم النشر والاشتراك والعربون منفصلة.</p>
      <div className="workspace-columns"><form className="workspace-form" onSubmit={topup}><h2>شحن الرصيد</h2><label>المبلغ بالدينار<input required type="number" min="0.001" max="100000" step="0.001" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>طريقة الدفع<select required value={provider} onChange={(e) => setProvider(e.target.value)}><option value="">اختر مزود الدفع</option>{providers.map((p) => <option key={p.code} value={p.code}>{p.name}</option>)}</select></label><button className="auth-submit" disabled={busy || !providers.length}><CreditCard size={17} />متابعة الدفع</button>{!providers.length && <p>الشحن الإلكتروني غير متاح حتى تفعيل مزود رسمي.</p>}</form>
      <form className="workspace-form" onSubmit={(e) => { e.preventDefault(); if (confirm(`طلب استرداد ${amount} د.ل؟ يُحجز المبلغ حتى تنفيذ التحويل أو رفض الطلب.`)) void run(() => api('wallet/withdrawals', 'POST', { amountLyd: amount, reason, idempotencyKey: crypto.randomUUID() })); }}><h2>طلب استرداد</h2><label>المبلغ بالدينار<input required type="number" min="0.001" step="0.001" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>السبب وطريقة التواصل<input required minLength={3} maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} /></label><button className="auth-submit" disabled={busy}>إرسال الطلب</button></form></div>
      <h2>طلبات الدفع</h2>{orders.map((o) => <article className="account-order" key={o.id}><div><strong>{names[o.type] ?? o.type}</strong><p>{statuses[o.status] ?? o.status}</p></div><strong>{money(o.totalLyd)}</strong>{o.status === 'PaymentPending' && o.type !== 'WalletRecharge' && <button disabled={busy} onClick={() => { if (confirm(`خصم ${money(o.totalLyd)} من المحفظة؟`)) void run(() => api(`payments/orders/${o.id}/wallet`, 'POST', { idempotencyKey: crypto.randomUUID() })); }}><Wallet size={17} />الدفع من المحفظة</button>}</article>)}
      <h2>سجل الحركات</h2>{wallet?.entries.map((e) => <div className="account-order" key={e.id}><span>{names[e.type] ?? 'حركة مالية'}</span><strong style={{ color: e.direction === 'Credit' ? '#218653' : '#bc2933' }}>{e.direction === 'Credit' ? '+' : '-'} {money(e.amountLyd)}</strong><time>{new Date(e.createdAt).toLocaleString('ar-LY')}</time></div>)}<h2>طلبات الاسترداد</h2>{wallet?.withdrawals.map((w) => <div className="account-order" key={w.id}><span>{statuses[w.status]}</span><strong>{money(w.amountLyd)}</strong></div>)}</>}
    {tab === 'subscriptions' && <><p>{subscriptions?.required ? 'اشتراك نشر فعّال مطلوب لإنشاء المزاد.' : 'اشتراك النشر اختياري حالياً.'}</p>{subscriptions?.subscriptions.map((s) => <article className="account-order" key={s.id}><strong>{s.plan.name}</strong><span>{statuses[s.status]}</span><span>{s.usedAuctions}/{s.plan.auctionLimit ?? 'غير محدود'} مزاد</span><time>{s.endsAt && new Date(s.endsAt).toLocaleString('ar-LY')}</time></article>)}<h2>الباقات المتاحة</h2><section className="workspace-plans">{subscriptions?.plans.map((p) => <article key={p.id}><h3>{p.name}</h3><strong>{money(p.priceLyd)}</strong><p>{p.durationDays} يوم · {p.auctionLimit ?? 'غير محدود'} مزاد</p><button className="auth-submit" disabled={busy} onClick={() => { if (confirm(`${p.name}: ${money(p.priceLyd)}. التفعيل بعد الدفع، ورسوم إدراج المركبة منفصلة.`)) void run(async () => { await api('subscriptions', 'POST', { planId: p.id, idempotencyKey: crypto.randomUUID() }); setTab('wallet'); }, 'أُنشئ طلب الاشتراك. أكمل الدفع.'); }}>اختيار الباقة</button></article>)}</section>{subscriptions && !subscriptions.plans.length && <p>لا توجد باقات متاحة. تواصل مع الإدارة.</p>}</>}
    {tab === 'requests' && <><div className="workspace-tabs"><button aria-pressed={incoming} onClick={() => setIncoming(true)}>واردة</button><button aria-pressed={!incoming} onClick={() => setIncoming(false)}>مرسلة</button></div><h2>طلبات الشراء</h2>{rows.sales.filter((r) => r.incoming === incoming).map((r) => card(r, false))}<h2>طلبات الفحص</h2>{rows.inspections.filter((r) => r.incoming === incoming).map((r) => card(r, true))}</>}
    {tab === 'favorites' && <>{!favorites.length && <p>المفضلة فارغة</p>}{favorites.map((v) => <article className="account-order" key={v.id}><a href={`/vehicles/${v.id}`}>{v.make} {v.model} {v.year}</a><button title="إزالة من المفضلة" disabled={busy} onClick={() => void run(() => api(`account/favorites/${v.id}`, 'DELETE'))}><Heart size={19} fill="currentColor" /></button></article>)}</>}
    {tab === 'settings' && <><form className="workspace-form" onSubmit={(e) => { e.preventDefault(); void run(() => api('workspace/settings', 'PATCH', { fullName: name, ...preferences })); }}><label>الاسم<input required minLength={2} maxLength={100} value={name} onChange={(e) => setName(e.target.value)} /></label>{Object.entries({ pushEnabled: 'إشعارات الهاتف', auctionNotifications: 'تنبيهات المزادات', messageNotifications: 'إشعارات الرسائل' }).map(([key, label]) => <label key={key} className="workspace-checkbox"><input type="checkbox" checked={preferences[key as keyof typeof preferences]} onChange={(e) => setPreferences({ ...preferences, [key]: e.target.checked })} />{label}</label>)}<button className="auth-submit" disabled={busy}><Save size={17} />حفظ الإعدادات</button></form><form className="workspace-form" onSubmit={(e) => { e.preventDefault(); void run(async () => { await api('workspace/password', 'POST', { currentPassword, newPassword }); await fetch('/api/auth/logout', { method: 'POST' }); location.href = '/auth'; }); }}><h2>الأمان</h2><label>كلمة المرور الحالية<input required type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></label><label>كلمة المرور الجديدة<input required type="password" minLength={12} maxLength={72} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></label><button className="auth-submit" disabled={busy}><Lock size={17} />تغيير كلمة المرور والخروج من الجلسات</button></form><div className="workspace-actions">{[['terms', 'الشروط والأحكام'], ['privacy', 'الخصوصية'], ['auction-rules', 'قواعد المزاد'], ['consumer-protection', 'حماية المستهلك']].map(([s,l]) => <a key={s} href={`/content/${s}`}>{l}</a>)}</div></>}
    {report && <form className="workspace-form" onSubmit={(e) => { e.preventDefault(); const { id, ...body } = report; void run(async () => { await api(`workspace/inspections/${id}/report`, 'POST', body); setReport(null); }); }}><h2>تقرير الفحص</h2>{[['technicianNotes','نتائج الفحص والعيوب'],['recommendations','التوصيات'],['engine','المحرك'],['transmission','القير'],['electric','الكهرباء'],['chassis','الشاصي']].map(([key,label]) => <label key={key}>{label}<textarea required minLength={key === 'technicianNotes' ? 10 : 2} maxLength={500} value={report[key as keyof typeof report]} onChange={(e) => setReport({ ...report, [key]: e.target.value })} /></label>)}<label>التقييم من 100<input required type="number" min={0} max={100} value={report.overallScore} onChange={(e) => setReport({ ...report, overallScore: Number(e.target.value) })} /></label><button disabled={busy} className="auth-submit">إرسال التقرير</button></form>}
    {review && <form className="workspace-form" onSubmit={(e) => { e.preventDefault(); void run(async () => { await api(`${review.kind}/${review.id}/reviews`, 'POST', { rating: review.rating, comment: review.comment }); setReview(null); }); }}><h2>تقييم الخدمة</h2><label>التقييم<select value={review.rating} onChange={(e) => setReview({ ...review, rating: Number(e.target.value) })}>{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label><label>تعليق<textarea maxLength={1000} value={review.comment} onChange={(e) => setReview({ ...review, comment: e.target.value })} /></label><button className="auth-submit" disabled={busy}><Star size={17} />حفظ التقييم</button></form>}
  </main>;
}
